### ISSUE TITLE
Question - Is It Safe To Remove This Custom Integration?

### ISSUE THREAD

**Issue by clearwave1** [perdue/homeassistant-blink#2]
@perdue - thanks for all your help with this.

I noticed your changes are finally integrated into HA 2023.7.0

Have you tried this yet? Is it now safe to remove your custom integration?

Thanks in advance for your input.

**Comment by perdue** [comment]
Thanks for letting me know!

I have been waiting for my commit to make it into a release because I am using the [save recent clips service](https://www.home-assistant.io/integrations/blink/#save-all-recent-clips-locally-on-a-schedule).  So I didn't update my Home Assistant server with any of the June releases.

The 2023.7.0 includes this service, so I believe you can safely remove the custom integration.  If you are not using the "save recent clips" service, then any of the June releases would have worked for you since they included the `blinkpy` updates already.

**Comment by clearwave1** [comment]
Thanks for getting back to me. I guess I just delete the custom folder and restart?

**Comment by perdue** [comment]
That will remove the custom integration.  You will still need to update to the 2023.7.0 version of `core` though.

**Comment by clearwave1** [comment]
I've already updated to that version. I'll rename the folder and restart to play it safe.

I'll let you know shortly how it goes.

**Comment by perdue** [comment]
Was it a good outcome?  No surprises?

**Comment by clearwave1** [comment]
Sorry for the late response. We're in the middle of major thunderstorms here and I was waiting for a break to test this since my camera is outside.

I just did the restart and while it missed the first clip, after waiting a bit it seems to be working again with the custom folder renamed so I think all is properly integrated now.

Thanks again for your work on this.

**Comment by perdue** [comment]
I just removed my custom integration and deployed the most recent HA release.  All looks good.
